### ISSUE TITLE
Cant get sync over HTTP

### ISSUE THREAD

**Issue by Subhajitdas298** [jeelabs/esp-link#160] opened 2016-06-20 15:39 UTC
Log:

> m/sync: 200, 12ms, h=20144
> 528364> UART 9600 baud
> 528364> MCU reset gpio0
> 528378> HTTP GET /pgm/sync: 200, 33ms, h=20144
> 528572> HTTP GET /pgm/sync: 200, 22ms, h=20144
> 528734> HTTP GET /pgm/sync: 200, 57ms, h=20144
> 528767> UART 57600 baud
> 528767> MCU reset gpio0
> 528896> HTTP GET /pgm/sync: 200, 57ms, h=20144
> 529049> HTTP GET /pgm/sync: 200, 48ms, h=20144
> 529170> UART 115200 baud
> 529170> MCU reset gpio0
> 529202> HTTP GET /pgm/sync: 200, 49ms, h=20144
> 529366> HTTP GET /pgm/sync: 200, 59ms, h=20144
> 529520> HTTP GET /pgm/sync: 200, 49ms, h=20144
> 529573> UART 115200 baud
> 529573> MCU reset gpio0
> 529673> HTTP GET /pgm/sync: 200, 49ms, h=20144
> 529835> HTTP GET /pgm/sync: 200, 58ms, h=20144
> 529975> UART 9600 baud
> 529976> MCU reset gpio0
> 529998> HTTP GET /pgm/sync: 200, 58ms, h=20144
> 530152> HTTP GET /pgm/sync: 200, 49ms, h=20144
> 530316> HTTP GET /pgm/sync: 200, 58ms, h=20144
> 530378> UART 57600 baud
> 530378> MCU reset gpio0
> 530469> HTTP GET /pgm/sync: 200, 48ms, h=20144
> 530621> HTTP GET /pgm/sync: 200, 48ms, h=20144
> 530774> HTTP GET /pgm/sync: 200, 48ms, h=20144
> 530780> UART 115200 baud
> 530781> MCU reset gpio0
> 530937> HTTP GET /pgm/sync: 200, 58ms, h=20144
> 531089> HTTP GET /pgm/sync: 200, 48ms, h=20144
> 531183> UART 115200 baud
> 531183> MCU reset gpio0
> 531585> OB sync abandoned after timeout, state=0 syncCnt=144
> 531586> UART 115200 baud
> 531586> OB init

Tried with ESP-12E and ESP-01.
Now whats happening?
Reset is OK over HTTP, not over Serial bridge as I said earlier.

**Comment by tve** [comment] 2016-06-20 17:02
Duplicate of #157 

In the end, I don't know what you're attaching nor what the circuit is. Looks like one of reset, TX, or RX is not connected properly.

**Closed as completed by tve** 2016-06-20 17:02 UTC
Labels: duplicate
