### ISSUE TITLE
ATO programming of Arduino MEGA, does anyone have this working over ESP-LINK V3?

### ISSUE THREAD

**Issue by WheresWally** [jeelabs/esp-link#223] opened 2016-11-29 12:36 UTC
I have ESP8266-01 with V3 ESP-LINK
The baud is universally set to 115200.
I can flash a UNO 100% of the time using the the HTTP upload method.
Fails when using the HTTP method to a MEGA 

```When trying to upload to a MEGA I use
avrdude -Cavrdude.conf -D -V -patmega2560 -carduino -Pnet:192.168.0.20:2323 -b115200 -Uflash:w:BrydenWeatherMC-MEGA.ino.hex
```

and get ...

```
avrdude: ser_drain(): read error: The parameter is incorrect.

avrdude: ser_drain(): read error: The parameter is incorrect.

avrdude: ser_drain(): read error: The parameter is incorrect.

avrdude: stk500_getsync() attempt 1 of 10: not in sync: resp=0x62
avrdude: stk500_getsync() attempt 2 of 10: not in sync: resp=0x20
avrdude: stk500_getsync() attempt 3 of 10: not in sync: resp=0x66
avrdude: stk500_getsync() attempt 4 of 10: not in sync: resp=0x72
avrdude: stk500_getsync() attempt 5 of 10: not in sync: resp=0x65
avrdude: stk500_getsync() attempt 6 of 10: not in sync: resp=0x65
avrdude: stk500_getsync() attempt 7 of 10: not in sync: resp=0x4d
avrdude: stk500_getsync() attempt 8 of 10: not in sync: resp=0x65
avrdude: stk500_getsync() attempt 9 of 10: not in sync: resp=0x6d
avrdude: stk500_getsync() attempt 10 of 10: not in sync: resp=0x6f
avrdude: ser_drain(): read error: The parameter is incorrect.

avrdude done.  Thank you.
```

the debug shows
```
653961> Accept port 2323, conn=0x3fff7590, pool slot 0
654469> MCU Reset=gpio0 ISP=gpio-1
```

if I use port 23
```
807015> Accept port 23, conn=0x3fff74d8, pool slot 0
807460> MCU Reset=gpio0 ISP=gpio-1
808398> serbridge: connection reset err=-9
```

BTW the Reset uController function does work so that is connected correctly.

Sending
```
curl -m 1 -XPOST http://192.168.0.20/pgm/sync
``` 
gives the following
```
   477> OB no sync response @115200 baud
   477> UART 115200 baud
   478> MCU reset gpio0
  1080> OB no sync response @115200 baud
  1081> UART 9600 baud
  1081> MCU reset gpio0
  1683> OB no sync response @9600 baud
  1683> UART 57600 baud
  1683> MCU reset gpio0
  2285> OB no sync response @57600 baud
  2285> UART 115200 baud
  2286> MCU reset gpio0
  2888> OB no sync response @115200 baud
  2888> UART 115200 baud
  2888> MCU reset gpio0
  3491> OB abandoned after 9 attempts
  3491> UART 115200 baud
  3491> OB init
```

**Comment by 9600** [comment] 2016-11-29 13:07
Hello, you called?

**Comment by WheresWally** [comment] 2016-11-30 01:40
I did call, and I said "Help me Please"
Any idea how to make the ESP-LINK program an attached uController  Arduino MEGA

**Comment by CharlyBrok** [comment] 2016-11-30 07:22
Is it the same issue as https://github.com/jeelabs/esp-link/issues/87 ?

**Comment by WheresWally** [comment] 2016-11-30 14:13
Yes it is, Thanks for linking to issue #[87](https://github.com/jeelabs/esp-link/issues/87) ?

**Comment by WheresWally** [comment] 2016-11-30 14:14
oops

**Comment by ramarro123** [comment] 2016-11-30 15:47
@tve it's this project still maintained?

**Comment by tve** [comment] 2016-11-30 16:27
Yup, but it's "feature complete" for my needs, so I don't have a ton of time to add new features. The last round of new features have been added by others and I integrated them. I don't have any MEGA so I'm unlikely to be able to add MEGA programming myself..

**Comment by lunix80** [comment] 2016-11-30 16:37
What a pity! With the use of MEGA it will be super!

**Comment by tve** [comment] 2016-11-30 16:41
If you feel this way, it would be awesome if you could contribute a pull request ;-)

**Comment by tve** [comment] 2016-11-30 17:24
This is a duplicate of #87

**Closed as completed by tve** 2016-11-30 17:24 UTC
