### ISSUE TITLE
Am I flashing something wrong?

### ISSUE THREAD

**Issue by Subhajitdas298** [jeelabs/esp-link#161] opened 2016-06-20 15:43 UTC
boot_1.4(b1).bin @ 0x00000
user1.bin            @ 0x01000
blank.bin            @ 0x3FE000

I am getting a lot of error, as my previous posts suggest.

**Comment by tve** [comment] 2016-06-20 17:03
Duplicate of #157

**Closed as completed by tve** 2016-06-20 17:03 UTC
Labels: duplicate
