### ISSUE TITLE
add parity support

### ISSUE THREAD

**Issue by jcw** [jeelabs/esp-link#201] opened 2016-10-18 18:49 UTC
To support re-flashing STM32 µC's, the ESP-Link would need to support 8E0 parity.
Telnet already has the proper definitions for it, see [RFC 2217](https://tools.ietf.org/html/rfc2217), section 2.
Would it be possible to add this?

**Comment by tve** [comment] 2016-10-23 00:37
duplicate of #98

**Closed as completed by tve** 2016-10-23 00:37 UTC
Labels: enhancement
